# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

# - id: doi:10.1016/j.csbj.2020.05.017
#   image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp


- id: arXiv:2411.00508
  image: images/clip-rt.png
  buttons:
    - type: source
      text: Github
      link: https://github.com/gicheonkang/clip-rt
    - type: website
      text: Paper
      link: https://clip-rt.github.io/
  publisher: RSS 2025

- id: arXiv:2403.12449
  publisher: Proceedings of the IEEE International Conference on Robotics and Automation (ICRA 2024)
- id: arXiv:2309.07759
  publisher: Proceedings of the IEEE International Conference on Robotics and Automation (ICRA 2024)
- id: arXiv:2403.06880
  publisher: Proceedings of the 38th Annual AAAI Conference on Artificial Intelligence (AAAI 2024)
- id: arXiv:2402.08963
  publisher: Proceedings of the 38th Annual AAAI Conference on Artificial Intelligence (AAAI 2024)
- id: arXiv:2307.05963
  publisher: Proceedings of IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS 2023)
- id: arXiv:2304.08204
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR 2023)
- id: arXiv:2211.02291
  publisher: Advances in Neural Information Processing Systems 35 (NeurIPS 2022)
- id: arXiv:2210.11201
  publisher: Advances in Neural Information Processing Systems 35 (NeurIPS 2022)
- id: arXiv:2210.12617
  publisher: Proceedings of the 2022 Conference on Empirical Methods in Natural Language Processing (EMNLP 2022)
- id: arXiv:2112.05907
  publisher: Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR 2022)
- id: arXiv:2210.17052
  publisher: Neural Information Processing Systems Workshops
- id: arXiv:2208.04832
  publisher: Proceedings of the ICML Complex Feedback in Online Learning Workshop (ICML 2022)
- id: arXiv:1907.01709
  publisher: Learning and Reasoning with Graph-Structured Representations, ICML 2019
- id: arXiv:1904.00623
  publisher: Story-Enabled Intelligence, AAAI Spring Symposium 2019 (AAAI SSS-19)
- id: arXiv:1901.09066
  publisher: AAAI-19 Workshop on Network Interpretability for Deep Learning
- id: arXiv:1901.08553
  publisher: AAAI-19 Workshop on Network Interpretability for Deep Learning
- id: arXiv:1805.10973
  publisher: Storytelling Workshop, NAACL 2018
